# Generated by Django 4.0.3 on 2022-04-03 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoconf', '0004_alter_profile_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
